### PR TITLE
Updated Docusaurus version to 2.2.0 | NOT BETA ANYMORE 🚀

### PR DESCRIPTION
**Pull request by Mercurial**
Along with the update I also moved the theming code to `index.tsx` instead of editing the internal layout of Docusaurus (they call it swizzling), which was really not needed in the first place.

Other NPM dependencies have also been updated

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
This seems to break the dark theme

**Comment by Mercurial** [comment]
> This seems to break the dark theme

Oh that's weird this is what I see on my side: 
image

Cleared `.docusaurus` and `build` folder just to make sure it wasn't cached and cleared browser cache, and `yarn build && yarn serve`

Could it be a cache issue ?

**Comment by SebastienGllmt** [comment]
Maybe your branch isn't rebased on latest main?

**Comment by Mercurial** [comment]
> Maybe your branch isn't rebased on latest main?

Good point, pulled from latest `main` branch rebuilt everything and even deployed gh-pages version of this PR: http://gh.adaph.io/ 

I can't seem to find any issues. 🤷🏻

**Pull request merged**
