### PR TITLE
Add documentation for Begin Wallet 🚀

### PR DESCRIPTION
**Pull request by francisluz**
Hey @SebastienGllmt just adding our Begin wallet on the docs.

### CODE REVIEW

**Review by SebastienGllmt — APPROVED** [review]
LGTM

**Comment by francisluz** [comment]
Hi @SebastienGllmt when the website gets updated? Thanks

**Comment by SebastienGllmt** [comment]
@francisluz my bad. Should be live now

**Comment by francisluz** [comment]
> @francisluz my bad. Should be live now

No problem at all. Appreciate 😉

**Pull request merged**
